# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('baseLevel', models.IntegerField(verbose_name='base level')),
                ('skillName', models.CharField(max_length=50, verbose_name='skill')),
                ('skillDescription', models.CharField(max_length=500)),
                ('isCurrentClassPrimary', models.BooleanField()),
                ('generation', models.IntegerField(choices=[(1, 'Generation One'), (2, 'Generation Two'), (3, 'Generation Three')], default=1, verbose_name='generation')),
                ('image_static', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Character Classes',
            },
        ),
        migrations.CreateModel(
            name='CharacterClassBonuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='class name')),
            ],
            options={
                'verbose_name': 'Character Class Category',
                'verbose_name_plural': 'Character Class Categories',
            },
        ),
        migrations.CreateModel(
            name='CharacterClassCategoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromClassCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_Class_Category', to='pyfeck.CharacterClassCategory')),
                ('toClassCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_Class_Category', to='pyfeck.CharacterClassCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassCompoundStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField()),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_class', to='pyfeck.CharacterClass')),
                ('toClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_class', to='pyfeck.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('minLevel', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth', models.IntegerField()),
                ('cap', models.IntegerField()),
                ('guardStanceBonus', models.IntegerField()),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependentCharacter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_Character', to='pyfeck.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth', models.IntegerField()),
                ('base', models.IntegerField()),
                ('cap_modifier', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSupportLevelStatBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attackStanceBonus', models.IntegerField()),
                ('guardStanceBonus', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterWeaponRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundStatCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Compound Stat Category',
                'verbose_name_plural': 'Compound Stat Categories',
            },
        ),
        migrations.CreateModel(
            name='SexCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='sex')),
            ],
            options={
                'verbose_name': 'Sex Category',
                'verbose_name_plural': 'Sex Categories',
            },
        ),
        migrations.CreateModel(
            name='StatCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Stat Category',
                'verbose_name_plural': 'Stat Categories',
            },
        ),
        migrations.CreateModel(
            name='SupportLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SupportLevelAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Support Level Availability',
                'verbose_name_plural': 'Support Level Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image_static', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.WeaponRank', verbose_name='weapon rank'),
        ),
        migrations.AddField(
            model_name='supportlevel',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.SupportLevelAvailability'),
        ),
        migrations.AddField(
            model_name='characterweaponrank',
            name='base_weapon_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.WeaponRank', verbose_name='character base rank for weapon'),
        ),
        migrations.AddField(
            model_name='characterweaponrank',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character'),
        ),
        migrations.AddField(
            model_name='characterweaponrank',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Weapon'),
        ),
        migrations.AddField(
            model_name='charactersupportlevelstatbonus',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.StatCategory'),
        ),
        migrations.AddField(
            model_name='charactersupportlevelstatbonus',
            name='supportLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.SupportLevel'),
        ),
        migrations.AddField(
            model_name='characterstat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.StatCategory'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='supportLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.SupportLevel'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='supportedCharacter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_Character', to='pyfeck.Character'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='supportingCharacter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_Character', to='pyfeck.Character'),
        ),
        migrations.AddField(
            model_name='characterclassweapon',
            name='max_weapon_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.WeaponRank'),
        ),
        migrations.AddField(
            model_name='characterclassweapon',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Weapon'),
        ),
        migrations.AddField(
            model_name='characterclassstat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.StatCategory'),
        ),
        migrations.AddField(
            model_name='characterclasscompoundstat',
            name='compoundStatCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CompoundStatCategory'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClassCategory'),
        ),
        migrations.AddField(
            model_name='character',
            name='currentClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass'),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.SexCategory'),
        ),
        migrations.AddField(
            model_name='character',
            name='primaryClassCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_Class_Category', to='pyfeck.CharacterClassCategory', verbose_name='primary class'),
        ),
        migrations.AddField(
            model_name='character',
            name='secondaryClassCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_Class_Category', to='pyfeck.CharacterClassCategory', verbose_name='secondary class'),
        ),
    ]
