# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive', models.IntegerField()),
                ('tier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassBonuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassCategoryPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_category', to='pyfeck.CharacterClassCategory')),
                ('toCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_category', to='pyfeck.CharacterClassCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('minLevel', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClassCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='stat',
            name='statCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.StatCategory'),
        ),
        migrations.AddField(
            model_name='characterclassweapon',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Weapon'),
        ),
        migrations.AddField(
            model_name='characterclassstat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Stat'),
        ),
        migrations.AddField(
            model_name='characterclassbonuses',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Stat'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClassCategory'),
        ),
        migrations.AddField(
            model_name='character',
            name='primaryClassCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClassCategory'),
        ),
    ]
