# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pyfeck.WeaponRank'),
            preserve_default=False,
        ),
    ]
