# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='isCurrentClassPrimary',
        ),
        migrations.AlterField(
            model_name='characterstat',
            name='base',
            field=models.IntegerField(verbose_name='base'),
        ),
        migrations.AlterField(
            model_name='characterstat',
            name='cap_modifier',
            field=models.IntegerField(verbose_name='cap modifier'),
        ),
        migrations.AlterField(
            model_name='characterstat',
            name='growth',
            field=models.IntegerField(verbose_name='personal growth'),
        ),
        migrations.AlterField(
            model_name='statcategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='stat'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.WeaponRank', verbose_name='rank'),
        ),
    ]
