# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0002_auto_20160320_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='statCategory',
        ),
        migrations.AlterModelOptions(
            name='characterclasscategory',
            options={'verbose_name': 'Character Class Category', 'verbose_name_plural': 'Character Class Categories'},
        ),
        migrations.AlterModelOptions(
            name='statcategory',
            options={'verbose_name': 'Stat Category', 'verbose_name_plural': 'Stat Categories'},
        ),
        migrations.RemoveField(
            model_name='characterclassbonuses',
            name='stat',
        ),
        migrations.AddField(
            model_name='characterclassstat',
            name='growth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characterclassstat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.StatCategory'),
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
