# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0003_auto_20160320_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClassCompoundStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompoundStatCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='passive',
        ),
        migrations.AddField(
            model_name='characterclasscompoundstat',
            name='characterClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass'),
        ),
        migrations.AddField(
            model_name='characterclasscompoundstat',
            name='compoundStatCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CompoundStatCategory'),
        ),
    ]
