# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0005_auto_20160328_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStatBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStatGrowth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SexCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='characterclass',
            options={'verbose_name_plural': 'Character Classes'},
        ),
        migrations.AlterModelOptions(
            name='compoundstatcategory',
            options={'verbose_name': 'Compound Stat Category', 'verbose_name_plural': 'Compound Stat Categories'},
        ),
        migrations.RenameField(
            model_name='character',
            old_name='level',
            new_name='baseLevel',
        ),
        migrations.RemoveField(
            model_name='character',
            name='primaryClassCategory',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='character',
            name='primaryClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='characterClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterstatgrowth',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character'),
        ),
        migrations.AddField(
            model_name='characterstatgrowth',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.StatCategory'),
        ),
        migrations.AddField(
            model_name='characterstatbase',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character'),
        ),
        migrations.AddField(
            model_name='characterstatbase',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.StatCategory'),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pyfeck.SexCategory'),
            preserve_default=False,
        ),
    ]
