# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0006_auto_20160519_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprimaryclassweapons',
            name='character',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character'),
            preserve_default=False,
        ),
    ]
