# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0006_auto_20160328_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='CharacterClassSkill',
        ),
        migrations.AddField(
            model_name='character',
            name='skillDescription',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='skillName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
