# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0007_auto_20160328_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclassweapon',
            name='max_weapon_rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pyfeck.WeaponRank'),
            preserve_default=False,
        ),
    ]
