# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0007_characterprimaryclassweapons_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterprimaryclassweapons',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character'),
        ),
        migrations.AlterField(
            model_name='characterprimaryclassweapons',
            name='classWeapon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClassWeapon'),
        ),
    ]
