# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0008_characterclassweapon_max_weapon_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterWeaponRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_weapon_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.WeaponRank')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Weapon')),
            ],
        ),
    ]
