# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0009_characterweaponrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth', models.IntegerField()),
                ('base', models.IntegerField()),
                ('cap_modifier', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.StatCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='characterstatbase',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterstatbase',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='characterstatgrowth',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterstatgrowth',
            name='stat',
        ),
        migrations.AddField(
            model_name='characterclassstat',
            name='cap',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CharacterStatBase',
        ),
        migrations.DeleteModel(
            name='CharacterStatGrowth',
        ),
    ]
