# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0010_auto_20160519_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPrimaryClassWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_weapon_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.WeaponRank', verbose_name='character base rank for weapon')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.Character')),
                ('classWeapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfeck.CharacterClassWeapon')),
            ],
        ),
        migrations.RemoveField(
            model_name='characterprimaryclassweapons',
            name='base_weapon_rank',
        ),
        migrations.RemoveField(
            model_name='characterprimaryclassweapons',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterprimaryclassweapons',
            name='weapon',
        ),
        migrations.DeleteModel(
            name='CharacterPrimaryClassWeapons',
        ),
    ]
