# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0010_auto_20160410_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='primaryClass',
            new_name='currentClass',
        ),
        migrations.AddField(
            model_name='character',
            name='isCurrentClassPrimary',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='primaryClassCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_Class_Category', to='pyfeck.CharacterClassCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='secondaryClassCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_Class_Category', to='pyfeck.CharacterClassCategory'),
            preserve_default=False,
        ),
    ]
