# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0011_auto_20160519_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='maxLevel',
            field=models.IntegerField(default=20, verbose_name='max level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='skillName',
            field=models.CharField(max_length=50, verbose_name='character skill'),
        ),
        migrations.AlterField(
            model_name='characterclassstat',
            name='cap',
            field=models.IntegerField(verbose_name='cap'),
        ),
        migrations.AlterField(
            model_name='characterclassstat',
            name='growth',
            field=models.IntegerField(verbose_name='growth'),
        ),
        migrations.AlterField(
            model_name='characterclassstat',
            name='guardStanceBonus',
            field=models.IntegerField(verbose_name='guard stance bonus'),
        ),
    ]
