# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfeck', '0013_auto_20160508_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='characterImage',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
    ]
